### ISSUE TITLE
Unexpected ">"

### ISSUE THREAD

**Issue by hopkins385** [breakerh/tiptap-image-resize#3]
**Bug Decription**
Hi guys, I'm getting the following error:

```
[vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/tiptap-imagresize/src/image.ts:29:19: ERROR: Unexpected ">"
```

**Steps To Reproduce**

1. Install package into laravel 9 project that is using vue and vite.
2. Remove the configure option entirely. 

```
onMounted(() => {
    editor.value = new Editor({
        extensions: [
            StarterKit,
            Image,
            ImageResize,
            TextAlign.configure({
                types: ['heading', 'paragraph'],
                alignments: ['left', 'center', 'right'],
                defaultAlignment: 'left',
            }),
        ],
        content: props.modelValue,
```

**Expected behavior**
Should fall back to default values

**Desktop (please complete the following information):**
 - OS: macOS Apple Silicon
 - using latest available version of all packages such as node, etc.

**Comment by hopkins385** [comment]
Ok .. wait ... after looking into the code .. is this extension only for react?

**Comment by breakerh** [comment]
@hopkins385 Corrects this is a React extension..
